In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb 

In [2]:
boston = pd.read_csv('BostonHousing.csv')
boston

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [3]:
output = boston['medv']
input = boston.drop('medv', axis = 1)

In [4]:
from sklearn.model_selection import train_test_split
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size= 0.2, random_state= 67)

In [5]:
from sklearn.linear_model import Ridge, Lasso
ridge_reg = Ridge()
ridge_reg.fit(input_train, output_train)

Ridge()

In [6]:
y_pred = ridge_reg.predict(input_train)

In [7]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("MAE:",mean_absolute_error(output_train, y_pred))
print("MSE:",mean_squared_error(output_train, y_pred))
print("r2_score:",r2_score(output_train, y_pred))

MAE: 3.426045670178618
MSE: 23.423223052054645
r2_score: 0.7421662093457727


In [8]:
y_pred_test = ridge_reg.predict(input_test)
y_pred_test

array([25.27083898, 15.45236382,  5.11654435, 24.17178973, 19.32102081,
       20.17195126, 26.78936917, 20.04927783, 36.00703184, 20.75220669,
       24.54330937, 28.54634032, 20.73238798, 23.28386136, 43.62307168,
       12.29546474, 19.6255419 , 20.65728775, 24.86514681, 12.9880803 ,
       25.3708609 , 25.0035803 , 34.11356125, 30.95054755, 20.58330937,
       10.5552034 , 14.72033156, 19.67696221, 17.9213161 , 20.20758747,
       20.12805513, 31.42811352, 33.40030542, 33.07679681, 18.49391475,
       19.65763247, 18.04567403, 18.24580381, 18.19256251, 30.22928284,
       19.1768638 , 19.88940029, 22.96890818, 24.35648325, 20.45403362,
       22.82648068, -0.39254693, 23.13293696, 29.42572011, 25.43508881,
       28.29131091,  7.87530528,  9.75886434, 19.27125821, 20.73943389,
       13.74716117, 14.39460665, 21.74219223, 24.09383516, 14.8676098 ,
       26.59092251, 32.09885529, 26.87381283,  2.16048395, 13.4602607 ,
       25.30044527, 19.84062708, 21.94229644,  6.66157906, 16.72

For test set

In [9]:
print("MSE:",mean_squared_error(output_test,y_pred_test))
print("MAE:",mean_absolute_error(output_test,y_pred_test))
print("r2_score:",r2_score(output_test,y_pred_test))

MSE: 18.334448716751023
MAE: 3.2004836859466996
r2_score: 0.6488069174732884


LASSO

In [10]:
lasso_reg = Lasso()
lasso_reg.fit(input_train,output_train)

Lasso()

In [11]:
y_predict = lasso_reg.predict(input_train)

In [14]:
lasso_reg.coef_

array([-0.07364851,  0.04118872, -0.        ,  0.        , -0.        ,
        1.06493252,  0.03333895, -0.63291745,  0.30461945, -0.01548871,
       -0.84697209,  0.00823084, -0.8352491 ])

In [12]:
print("MSE:", mean_squared_error(output_train, y_predict))
print("MAE:", mean_absolute_error(output_train, y_predict))
print("r2_score:", r2_score(output_train, y_predict))

MSE: 28.076104481648226
MAE: 3.7751368539844945
r2_score: 0.6909490880388252


In [13]:
y_predict_test = lasso_reg.predict(input_test)
print("MSE:",mean_squared_error(output_test,y_predict_test))
print("MAE:",mean_absolute_error(output_test,y_predict_test))
print("r2_score:",r2_score(output_test,y_predict_test))

MSE: 20.56042540374749
MAE: 3.4709978265738552
r2_score: 0.6061687325779523


In [16]:
lasso_reg.coef_

array([-0.07364851,  0.04118872, -0.        ,  0.        , -0.        ,
        1.06493252,  0.03333895, -0.63291745,  0.30461945, -0.01548871,
       -0.84697209,  0.00823084, -0.8352491 ])